FROM nginx:alpine

# Copiar archivos del frontend
COPY . /usr/share/nginx/html/
COPY images/ /usr/share/nginx/html/images/

# Copiar configuración de Nginx
#COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
